/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "mutation AccountAddressCreate($input: AddressInput!) {\n  accountAddressCreate(input: $input) {\n    address {\n      ...AddressDetails\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": typeof types.AccountAddressCreateDocument,
    "mutation AccountAddressDelete($id: ID!) {\n  accountAddressDelete(id: $id) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": typeof types.AccountAddressDeleteDocument,
    "mutation AccountAddressUpdate($id: ID!, $input: AddressInput!) {\n  accountAddressUpdate(id: $id, input: $input) {\n    address {\n      ...AddressDetails\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": typeof types.AccountAddressUpdateDocument,
    "mutation AccountRequestDeletion($redirectUrl: String!, $channel: String) {\n  accountRequestDeletion(redirectUrl: $redirectUrl, channel: $channel) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": typeof types.AccountRequestDeletionDocument,
    "mutation AccountSetDefaultAddress($id: ID!, $type: AddressTypeEnum!) {\n  accountSetDefaultAddress(id: $id, type: $type) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": typeof types.AccountSetDefaultAddressDocument,
    "mutation AccountUpdate($input: AccountInput!) {\n  accountUpdate(input: $input) {\n    user {\n      ...UserDetails\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": typeof types.AccountUpdateDocument,
    "fragment AddressDetails on Address {\n  id\n  firstName\n  lastName\n  companyName\n  streetAddress1\n  streetAddress2\n  city\n  cityArea\n  postalCode\n  countryArea\n  country {\n    code\n    country\n  }\n  phone\n}": typeof types.AddressDetailsFragmentDoc,
    "query CategoriesBySlug($slugs: [String!]!, $first: Int = 20) {\n  categories(filter: {slugs: $slugs}, first: $first) {\n    edges {\n      node {\n        id\n        slug\n        name\n      }\n    }\n  }\n}": typeof types.CategoriesBySlugDocument,
    "query ChannelsList {\n  channels {\n    id\n    name\n    slug\n    isActive\n    currencyCode\n    defaultCountry {\n      code\n    }\n  }\n}": typeof types.ChannelsListDocument,
    "mutation CheckoutAddLine($id: ID!, $productVariantId: ID!) {\n  checkoutLinesAdd(id: $id, lines: [{quantity: 1, variantId: $productVariantId}]) {\n    checkout {\n      id\n      lines {\n        id\n        quantity\n        variant {\n          name\n          product {\n            name\n          }\n        }\n      }\n    }\n    errors {\n      message\n    }\n  }\n}": typeof types.CheckoutAddLineDocument,
    "mutation CheckoutCreate($channel: String!, $languageCode: LanguageCodeEnum!, $metadata: [MetadataInput!]) {\n  checkoutCreate(\n    input: {channel: $channel, languageCode: $languageCode, lines: [], metadata: $metadata}\n  ) {\n    checkout {\n      id\n      email\n      lines {\n        id\n        quantity\n        totalPrice {\n          gross {\n            amount\n            currency\n          }\n        }\n        variant {\n          product {\n            id\n            name\n            slug\n            thumbnail(size: 256, format: WEBP) {\n              url\n              alt\n            }\n            category {\n              name\n            }\n          }\n          pricing {\n            price {\n              gross {\n                amount\n                currency\n              }\n            }\n          }\n          name\n          id\n        }\n      }\n      totalPrice {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n    errors {\n      field\n      code\n    }\n  }\n}": typeof types.CheckoutCreateDocument,
    "mutation CheckoutCustomerDetach($id: ID!) {\n  checkoutCustomerDetach(id: $id) {\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": typeof types.CheckoutCustomerDetachDocument,
    "mutation CheckoutDeleteLines($checkoutId: ID!, $lineIds: [ID!]!) {\n  checkoutLinesDelete(id: $checkoutId, linesIds: $lineIds) {\n    checkout {\n      id\n      lines {\n        id\n      }\n      channel {\n        slug\n      }\n    }\n    errors {\n      field\n      code\n    }\n  }\n}": typeof types.CheckoutDeleteLinesDocument,
    "query CheckoutFind($id: ID!, $languageCode: LanguageCodeEnum!) {\n  checkout(id: $id) {\n    id\n    email\n    lines {\n      id\n      quantity\n      totalPrice {\n        gross {\n          amount\n          currency\n        }\n      }\n      variant {\n        translation(languageCode: $languageCode) {\n          name\n        }\n        product {\n          id\n          name\n          slug\n          translation(languageCode: $languageCode) {\n            name\n          }\n          thumbnail(size: 256, format: WEBP) {\n            url\n            alt\n          }\n          category {\n            name\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n        }\n        pricing {\n          price {\n            gross {\n              amount\n              currency\n            }\n          }\n          priceUndiscounted {\n            gross {\n              amount\n              currency\n            }\n          }\n        }\n        name\n        id\n        selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {\n          attribute {\n            name\n            slug\n            inputType\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n          values {\n            name\n            value\n            translation(languageCode: $languageCode) {\n              name\n            }\n            file {\n              url\n            }\n          }\n        }\n        nonSelectionAttributes: attributes(variantSelection: NOT_VARIANT_SELECTION) {\n          attribute {\n            name\n            slug\n            inputType\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n          values {\n            name\n            value\n            translation(languageCode: $languageCode) {\n              name\n            }\n            file {\n              url\n            }\n          }\n        }\n      }\n    }\n    totalPrice {\n      gross {\n        amount\n        currency\n      }\n    }\n  }\n}": typeof types.CheckoutFindDocument,
    "mutation CheckoutLinesUpdate($checkoutId: ID!, $lines: [CheckoutLineUpdateInput!]!) {\n  checkoutLinesUpdate(id: $checkoutId, lines: $lines) {\n    checkout {\n      id\n      lines {\n        id\n        quantity\n        totalPrice {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n      totalPrice {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": typeof types.CheckoutLinesUpdateDocument,
    "query CurrentUser {\n  me {\n    ...UserDetails\n  }\n}": typeof types.CurrentUserDocument,
    "query CurrentUserOrderList($languageCode: LanguageCodeEnum!) {\n  me {\n    ...UserDetails\n    orders(first: 10) {\n      edges {\n        node {\n          ...OrderDetails\n        }\n      }\n    }\n  }\n}": typeof types.CurrentUserOrderListDocument,
    "query CurrentUserOrdersPaginated($first: Int, $after: String, $languageCode: LanguageCodeEnum!) {\n  me {\n    ...UserDetails\n    orders(first: $first, after: $after) {\n      edges {\n        node {\n          ...OrderDetails\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n}": typeof types.CurrentUserOrdersPaginatedDocument,
    "query CurrentUserProfile {\n  me {\n    ...UserDetails\n    dateJoined\n    addresses {\n      ...AddressDetails\n    }\n    defaultShippingAddress {\n      id\n    }\n    defaultBillingAddress {\n      id\n    }\n  }\n}": typeof types.CurrentUserProfileDocument,
    "fragment ProductLocaleSlugTranslations on Product {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}\n\nfragment CategoryLocaleSlugTranslations on Category {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}\n\nfragment CollectionLocaleSlugTranslations on Collection {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}\n\nfragment PageLocaleSlugTranslations on Page {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}": typeof types.ProductLocaleSlugTranslationsFragmentDoc,
    "fragment MenuItem on MenuItem {\n  id\n  name\n  level\n  translation(languageCode: $languageCode) {\n    name\n  }\n  category {\n    id\n    slug\n    name\n    translation(languageCode: $languageCode) {\n      name\n      slug\n    }\n  }\n  collection {\n    id\n    name\n    slug\n    translation(languageCode: $languageCode) {\n      name\n      slug\n    }\n  }\n  page {\n    id\n    title\n    slug\n    translation(languageCode: $languageCode) {\n      title\n      slug\n    }\n  }\n  url\n}\n\nquery MenuGetBySlug($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  menu(slug: $slug, channel: $channel) {\n    items {\n      ...MenuItem\n      children {\n        ...MenuItem\n        children {\n          ...MenuItem\n        }\n      }\n    }\n  }\n}": typeof types.MenuItemFragmentDoc,
    "fragment OrderFullDetails on Order {\n  id\n  number\n  created\n  status\n  statusDisplay\n  paymentStatus\n  isPaid\n  shippingAddress {\n    ...AddressDetails\n  }\n  billingAddress {\n    ...AddressDetails\n  }\n  subtotal {\n    gross {\n      amount\n      currency\n    }\n  }\n  shippingPrice {\n    gross {\n      amount\n      currency\n    }\n  }\n  total {\n    gross {\n      amount\n      currency\n    }\n    tax {\n      amount\n      currency\n    }\n  }\n  lines {\n    id\n    quantity\n    variant {\n      id\n      name\n      translation(languageCode: $languageCode) {\n        name\n      }\n      product {\n        id\n        name\n        slug\n        translation(languageCode: $languageCode) {\n          name\n        }\n        thumbnail(size: 256, format: WEBP) {\n          url\n          alt\n        }\n      }\n      pricing {\n        price {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n    }\n  }\n  fulfillments {\n    id\n    status\n    created\n    trackingNumber\n    lines {\n      id\n      quantity\n      orderLine {\n        id\n      }\n    }\n  }\n}\n\nquery OrderByNumber($first: Int, $languageCode: LanguageCodeEnum!) {\n  me {\n    orders(first: $first) {\n      edges {\n        node {\n          ...OrderFullDetails\n        }\n      }\n    }\n  }\n}": typeof types.OrderFullDetailsFragmentDoc,
    "fragment OrderDetails on Order {\n  id\n  number\n  created\n  total {\n    gross {\n      amount\n      currency\n    }\n  }\n  lines {\n    variant {\n      id\n      name\n      translation(languageCode: $languageCode) {\n        name\n      }\n      product {\n        id\n        name\n        description\n        slug\n        translation(languageCode: $languageCode) {\n          name\n        }\n        thumbnail(size: 256, format: WEBP) {\n          url\n          alt\n        }\n        category {\n          id\n          name\n        }\n      }\n      pricing {\n        price {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n    }\n    quantity\n  }\n  status\n  statusDisplay\n  paymentStatus\n}": typeof types.OrderDetailsFragmentDoc,
    "query PageGetBySlug($slug: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum) {\n  page(slug: $slug, slugLanguageCode: $slugLanguageCode) {\n    id\n    slug\n    title\n    seoTitle\n    seoDescription\n    content\n    translation(languageCode: $languageCode) {\n      title\n      seoTitle\n      seoDescription\n      content\n      slug\n    }\n    ...PageLocaleSlugTranslations\n  }\n}": typeof types.PageGetBySlugDocument,
    "mutation PasswordChange($newPassword: String!, $oldPassword: String!) {\n  passwordChange(newPassword: $newPassword, oldPassword: $oldPassword) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": typeof types.PasswordChangeDocument,
    "query ProductDetails($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum) {\n  product(slug: $slug, channel: $channel, slugLanguageCode: $slugLanguageCode) {\n    id\n    name\n    slug\n    description\n    seoTitle\n    seoDescription\n    isAvailable\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoTitle\n      seoDescription\n      slug\n    }\n    ...ProductLocaleSlugTranslations\n    thumbnail(size: 2048, format: WEBP) {\n      url\n      alt\n    }\n    media {\n      url(size: 2048, format: WEBP)\n      url256: url(size: 256, format: WEBP)\n      url512: url(size: 512, format: WEBP)\n      url1024: url(size: 1024, format: WEBP)\n      alt\n      type\n    }\n    category {\n      id\n      name\n      slug\n      translation(languageCode: $languageCode) {\n        name\n        slug\n      }\n    }\n    productType {\n      slug\n    }\n    productVariants(first: 1) {\n      totalCount\n    }\n    bestseller: assignedAttribute(slug: \"bestseller\") {\n      ... on AssignedBooleanAttribute {\n        value\n      }\n    }\n    pulseBestseller: assignedAttribute(slug: \"pulse-bestseller\") {\n      ... on AssignedBooleanAttribute {\n        value\n      }\n    }\n    assignedAttributes(limit: 50) {\n      attribute {\n        name\n        slug\n        translation(languageCode: $languageCode) {\n          name\n        }\n      }\n      ... on AssignedPlainTextAttribute {\n        plainText: value\n        plainTextTranslation: translation(languageCode: $languageCode)\n      }\n      ... on AssignedBooleanAttribute {\n        boolean: value\n      }\n      ... on AssignedNumericAttribute {\n        numeric: value\n      }\n      ... on AssignedSingleChoiceAttribute {\n        choice: value {\n          name\n          slug\n          translation(languageCode: $languageCode)\n        }\n      }\n      ... on AssignedMultiChoiceAttribute {\n        choices: value {\n          name\n          slug\n          translation(languageCode: $languageCode)\n        }\n      }\n    }\n    pricing {\n      priceRange {\n        start {\n          gross {\n            amount\n            currency\n          }\n        }\n        stop {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n    }\n  }\n}": typeof types.ProductDetailsDocument,
    "query ProductList($first: Int = 9, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  products(first: $first, channel: $channel) {\n    edges {\n      node {\n        ...ProductListItem\n      }\n    }\n  }\n}": typeof types.ProductListDocument,
    "query ProductListByCategory($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum, $first: Int, $after: String, $sortBy: ProductOrder, $filter: ProductFilterInput, $where: ProductWhereInput) {\n  category(slug: $slug, slugLanguageCode: $slugLanguageCode) {\n    id\n    name\n    slug\n    description\n    seoDescription\n    seoTitle\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoDescription\n      seoTitle\n      slug\n    }\n    ...CategoryLocaleSlugTranslations\n    backgroundImage(size: 2048, format: WEBP) {\n      url\n      alt\n    }\n    products(\n      first: $first\n      after: $after\n      channel: $channel\n      sortBy: $sortBy\n      filter: $filter\n      where: $where\n    ) {\n      edges {\n        node {\n          ...ProductListItem\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n}": typeof types.ProductListByCategoryDocument,
    "query ProductListByCollection($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum, $first: Int, $after: String, $sortBy: ProductOrder, $filter: ProductFilterInput, $where: ProductWhereInput) {\n  collection(slug: $slug, channel: $channel, slugLanguageCode: $slugLanguageCode) {\n    id\n    name\n    slug\n    description\n    seoDescription\n    seoTitle\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoDescription\n      seoTitle\n      slug\n    }\n    ...CollectionLocaleSlugTranslations\n    backgroundImage(size: 2048, format: WEBP) {\n      url\n      alt\n    }\n    products(\n      first: $first\n      after: $after\n      sortBy: $sortBy\n      filter: $filter\n      where: $where\n    ) {\n      edges {\n        node {\n          ...ProductListItem\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n}": typeof types.ProductListByCollectionDocument,
    "fragment ProductListItem on Product {\n  id\n  name\n  slug\n  created\n  translation(languageCode: $languageCode) {\n    name\n    slug\n  }\n  pricing {\n    priceRange {\n      start {\n        gross {\n          amount\n          currency\n        }\n      }\n      stop {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n    priceRangeUndiscounted {\n      start {\n        gross {\n          amount\n          currency\n        }\n      }\n      stop {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n  }\n  category {\n    id\n    name\n    slug\n    translation(languageCode: $languageCode) {\n      name\n      slug\n    }\n    backgroundImage(size: 1024, format: WEBP) {\n      url\n      alt\n    }\n    backgroundImage256: backgroundImage(size: 256, format: WEBP) {\n      url\n    }\n    backgroundImage512: backgroundImage(size: 512, format: WEBP) {\n      url\n    }\n  }\n  thumbnail(size: 1024, format: WEBP) {\n    url\n    alt\n  }\n  thumbnail256: thumbnail(size: 256, format: WEBP) {\n    url\n  }\n  thumbnail512: thumbnail(size: 512, format: WEBP) {\n    url\n  }\n  bestseller: assignedAttribute(slug: \"bestseller\") {\n    ... on AssignedBooleanAttribute {\n      value\n    }\n  }\n  pulseBestseller: assignedAttribute(slug: \"pulse-bestseller\") {\n    ... on AssignedBooleanAttribute {\n      value\n    }\n  }\n  productVariants(first: 50) {\n    totalCount\n    edges {\n      node {\n        id\n        selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {\n          attribute {\n            slug\n            name\n            inputType\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n          values {\n            name\n            slug\n            value\n            translation(languageCode: $languageCode) {\n              name\n            }\n            file {\n              url\n            }\n          }\n        }\n      }\n    }\n  }\n}": typeof types.ProductListItemFragmentDoc,
    "query ProductListPaginated($first: Int, $after: String, $last: Int, $before: String, $channel: String!, $languageCode: LanguageCodeEnum!, $sortBy: ProductOrder, $filter: ProductFilterInput, $where: ProductWhereInput) {\n  products(\n    first: $first\n    after: $after\n    last: $last\n    before: $before\n    channel: $channel\n    sortBy: $sortBy\n    filter: $filter\n    where: $where\n  ) {\n    totalCount\n    edges {\n      node {\n        ...ProductListItem\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      hasPreviousPage\n      startCursor\n      endCursor\n    }\n  }\n}": typeof types.ProductListPaginatedDocument,
    "query ProductVariantForPdp($id: ID, $sku: String, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  productVariant(id: $id, sku: $sku, channel: $channel) {\n    ...VariantDetails\n    product {\n      id\n      slug\n    }\n  }\n}": typeof types.ProductVariantForPdpDocument,
    "query ProductVariantsForPdp($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $first: Int!, $after: String) {\n  product(slug: $slug, channel: $channel) {\n    id\n    productVariants(first: $first, after: $after) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      edges {\n        node {\n          ...VariantDetails\n        }\n      }\n    }\n  }\n}": typeof types.ProductVariantsForPdpDocument,
    "query SearchProducts($search: String!, $sortBy: ProductOrderField!, $sortDirection: OrderDirection!, $first: Int, $after: String, $last: Int, $before: String, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  products(\n    first: $first\n    after: $after\n    last: $last\n    before: $before\n    channel: $channel\n    sortBy: {field: $sortBy, direction: $sortDirection}\n    filter: {search: $search}\n  ) {\n    totalCount\n    edges {\n      node {\n        ...ProductListItem\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      hasPreviousPage\n      endCursor\n      startCursor\n    }\n  }\n}": typeof types.SearchProductsDocument,
    "query StorefrontContentPages($channel: String!, $slugs: [String!]!, $languageCode: LanguageCodeEnum!) {\n  pages(channel: $channel, where: {slug: {oneOf: $slugs}}, first: 20) {\n    edges {\n      node {\n        ...StorefrontContentPage\n      }\n    }\n  }\n}\n\nfragment StorefrontContentPage on Page {\n  slug\n  isPublished\n  pageType {\n    slug\n  }\n  assignedAttributes {\n    attribute {\n      slug\n    }\n    ... on AssignedPlainTextAttribute {\n      plainText: value\n      plainTextTranslation: translation(languageCode: $languageCode)\n    }\n    ... on AssignedBooleanAttribute {\n      boolean: value\n    }\n    ... on AssignedNumericAttribute {\n      numeric: value\n    }\n    ... on AssignedSingleCollectionReferenceAttribute {\n      collection: value {\n        slug\n      }\n    }\n    ... on AssignedFileAttribute {\n      file: value {\n        url\n      }\n    }\n  }\n}": typeof types.StorefrontContentPagesDocument,
    "fragment UserDetails on User {\n  id\n  email\n  firstName\n  lastName\n  avatar {\n    url\n    alt\n  }\n}": typeof types.UserDetailsFragmentDoc,
    "fragment VariantDetails on ProductVariant {\n  id\n  name\n  sku\n  quantityAvailable\n  translation(languageCode: $languageCode) {\n    name\n  }\n  selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {\n    values {\n      name\n      slug\n      value\n      translation(languageCode: $languageCode) {\n        name\n      }\n      file {\n        url\n      }\n    }\n    attribute {\n      name\n      slug\n      inputType\n      translation(languageCode: $languageCode) {\n        name\n      }\n    }\n  }\n  nonSelectionAttributes: attributes(variantSelection: NOT_VARIANT_SELECTION) {\n    values {\n      name\n      slug\n      value\n      translation(languageCode: $languageCode) {\n        name\n      }\n      file {\n        url\n      }\n    }\n    attribute {\n      name\n      slug\n      inputType\n      translation(languageCode: $languageCode) {\n        name\n      }\n    }\n  }\n  media {\n    url(size: 2048, format: WEBP)\n    url256: url(size: 256, format: WEBP)\n    url512: url(size: 512, format: WEBP)\n    url1024: url(size: 1024, format: WEBP)\n    alt\n    type\n  }\n  pricing {\n    price {\n      gross {\n        currency\n        amount\n      }\n    }\n    priceUndiscounted {\n      gross {\n        currency\n        amount\n      }\n    }\n  }\n}": typeof types.VariantDetailsFragmentDoc,
};
const documents: Documents = {
    "mutation AccountAddressCreate($input: AddressInput!) {\n  accountAddressCreate(input: $input) {\n    address {\n      ...AddressDetails\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": types.AccountAddressCreateDocument,
    "mutation AccountAddressDelete($id: ID!) {\n  accountAddressDelete(id: $id) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": types.AccountAddressDeleteDocument,
    "mutation AccountAddressUpdate($id: ID!, $input: AddressInput!) {\n  accountAddressUpdate(id: $id, input: $input) {\n    address {\n      ...AddressDetails\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": types.AccountAddressUpdateDocument,
    "mutation AccountRequestDeletion($redirectUrl: String!, $channel: String) {\n  accountRequestDeletion(redirectUrl: $redirectUrl, channel: $channel) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": types.AccountRequestDeletionDocument,
    "mutation AccountSetDefaultAddress($id: ID!, $type: AddressTypeEnum!) {\n  accountSetDefaultAddress(id: $id, type: $type) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": types.AccountSetDefaultAddressDocument,
    "mutation AccountUpdate($input: AccountInput!) {\n  accountUpdate(input: $input) {\n    user {\n      ...UserDetails\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": types.AccountUpdateDocument,
    "fragment AddressDetails on Address {\n  id\n  firstName\n  lastName\n  companyName\n  streetAddress1\n  streetAddress2\n  city\n  cityArea\n  postalCode\n  countryArea\n  country {\n    code\n    country\n  }\n  phone\n}": types.AddressDetailsFragmentDoc,
    "query CategoriesBySlug($slugs: [String!]!, $first: Int = 20) {\n  categories(filter: {slugs: $slugs}, first: $first) {\n    edges {\n      node {\n        id\n        slug\n        name\n      }\n    }\n  }\n}": types.CategoriesBySlugDocument,
    "query ChannelsList {\n  channels {\n    id\n    name\n    slug\n    isActive\n    currencyCode\n    defaultCountry {\n      code\n    }\n  }\n}": types.ChannelsListDocument,
    "mutation CheckoutAddLine($id: ID!, $productVariantId: ID!) {\n  checkoutLinesAdd(id: $id, lines: [{quantity: 1, variantId: $productVariantId}]) {\n    checkout {\n      id\n      lines {\n        id\n        quantity\n        variant {\n          name\n          product {\n            name\n          }\n        }\n      }\n    }\n    errors {\n      message\n    }\n  }\n}": types.CheckoutAddLineDocument,
    "mutation CheckoutCreate($channel: String!, $languageCode: LanguageCodeEnum!, $metadata: [MetadataInput!]) {\n  checkoutCreate(\n    input: {channel: $channel, languageCode: $languageCode, lines: [], metadata: $metadata}\n  ) {\n    checkout {\n      id\n      email\n      lines {\n        id\n        quantity\n        totalPrice {\n          gross {\n            amount\n            currency\n          }\n        }\n        variant {\n          product {\n            id\n            name\n            slug\n            thumbnail(size: 256, format: WEBP) {\n              url\n              alt\n            }\n            category {\n              name\n            }\n          }\n          pricing {\n            price {\n              gross {\n                amount\n                currency\n              }\n            }\n          }\n          name\n          id\n        }\n      }\n      totalPrice {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n    errors {\n      field\n      code\n    }\n  }\n}": types.CheckoutCreateDocument,
    "mutation CheckoutCustomerDetach($id: ID!) {\n  checkoutCustomerDetach(id: $id) {\n    errors {\n      message\n      field\n      code\n    }\n  }\n}": types.CheckoutCustomerDetachDocument,
    "mutation CheckoutDeleteLines($checkoutId: ID!, $lineIds: [ID!]!) {\n  checkoutLinesDelete(id: $checkoutId, linesIds: $lineIds) {\n    checkout {\n      id\n      lines {\n        id\n      }\n      channel {\n        slug\n      }\n    }\n    errors {\n      field\n      code\n    }\n  }\n}": types.CheckoutDeleteLinesDocument,
    "query CheckoutFind($id: ID!, $languageCode: LanguageCodeEnum!) {\n  checkout(id: $id) {\n    id\n    email\n    lines {\n      id\n      quantity\n      totalPrice {\n        gross {\n          amount\n          currency\n        }\n      }\n      variant {\n        translation(languageCode: $languageCode) {\n          name\n        }\n        product {\n          id\n          name\n          slug\n          translation(languageCode: $languageCode) {\n            name\n          }\n          thumbnail(size: 256, format: WEBP) {\n            url\n            alt\n          }\n          category {\n            name\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n        }\n        pricing {\n          price {\n            gross {\n              amount\n              currency\n            }\n          }\n          priceUndiscounted {\n            gross {\n              amount\n              currency\n            }\n          }\n        }\n        name\n        id\n        selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {\n          attribute {\n            name\n            slug\n            inputType\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n          values {\n            name\n            value\n            translation(languageCode: $languageCode) {\n              name\n            }\n            file {\n              url\n            }\n          }\n        }\n        nonSelectionAttributes: attributes(variantSelection: NOT_VARIANT_SELECTION) {\n          attribute {\n            name\n            slug\n            inputType\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n          values {\n            name\n            value\n            translation(languageCode: $languageCode) {\n              name\n            }\n            file {\n              url\n            }\n          }\n        }\n      }\n    }\n    totalPrice {\n      gross {\n        amount\n        currency\n      }\n    }\n  }\n}": types.CheckoutFindDocument,
    "mutation CheckoutLinesUpdate($checkoutId: ID!, $lines: [CheckoutLineUpdateInput!]!) {\n  checkoutLinesUpdate(id: $checkoutId, lines: $lines) {\n    checkout {\n      id\n      lines {\n        id\n        quantity\n        totalPrice {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n      totalPrice {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": types.CheckoutLinesUpdateDocument,
    "query CurrentUser {\n  me {\n    ...UserDetails\n  }\n}": types.CurrentUserDocument,
    "query CurrentUserOrderList($languageCode: LanguageCodeEnum!) {\n  me {\n    ...UserDetails\n    orders(first: 10) {\n      edges {\n        node {\n          ...OrderDetails\n        }\n      }\n    }\n  }\n}": types.CurrentUserOrderListDocument,
    "query CurrentUserOrdersPaginated($first: Int, $after: String, $languageCode: LanguageCodeEnum!) {\n  me {\n    ...UserDetails\n    orders(first: $first, after: $after) {\n      edges {\n        node {\n          ...OrderDetails\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n}": types.CurrentUserOrdersPaginatedDocument,
    "query CurrentUserProfile {\n  me {\n    ...UserDetails\n    dateJoined\n    addresses {\n      ...AddressDetails\n    }\n    defaultShippingAddress {\n      id\n    }\n    defaultBillingAddress {\n      id\n    }\n  }\n}": types.CurrentUserProfileDocument,
    "fragment ProductLocaleSlugTranslations on Product {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}\n\nfragment CategoryLocaleSlugTranslations on Category {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}\n\nfragment CollectionLocaleSlugTranslations on Collection {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}\n\nfragment PageLocaleSlugTranslations on Page {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}": types.ProductLocaleSlugTranslationsFragmentDoc,
    "fragment MenuItem on MenuItem {\n  id\n  name\n  level\n  translation(languageCode: $languageCode) {\n    name\n  }\n  category {\n    id\n    slug\n    name\n    translation(languageCode: $languageCode) {\n      name\n      slug\n    }\n  }\n  collection {\n    id\n    name\n    slug\n    translation(languageCode: $languageCode) {\n      name\n      slug\n    }\n  }\n  page {\n    id\n    title\n    slug\n    translation(languageCode: $languageCode) {\n      title\n      slug\n    }\n  }\n  url\n}\n\nquery MenuGetBySlug($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  menu(slug: $slug, channel: $channel) {\n    items {\n      ...MenuItem\n      children {\n        ...MenuItem\n        children {\n          ...MenuItem\n        }\n      }\n    }\n  }\n}": types.MenuItemFragmentDoc,
    "fragment OrderFullDetails on Order {\n  id\n  number\n  created\n  status\n  statusDisplay\n  paymentStatus\n  isPaid\n  shippingAddress {\n    ...AddressDetails\n  }\n  billingAddress {\n    ...AddressDetails\n  }\n  subtotal {\n    gross {\n      amount\n      currency\n    }\n  }\n  shippingPrice {\n    gross {\n      amount\n      currency\n    }\n  }\n  total {\n    gross {\n      amount\n      currency\n    }\n    tax {\n      amount\n      currency\n    }\n  }\n  lines {\n    id\n    quantity\n    variant {\n      id\n      name\n      translation(languageCode: $languageCode) {\n        name\n      }\n      product {\n        id\n        name\n        slug\n        translation(languageCode: $languageCode) {\n          name\n        }\n        thumbnail(size: 256, format: WEBP) {\n          url\n          alt\n        }\n      }\n      pricing {\n        price {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n    }\n  }\n  fulfillments {\n    id\n    status\n    created\n    trackingNumber\n    lines {\n      id\n      quantity\n      orderLine {\n        id\n      }\n    }\n  }\n}\n\nquery OrderByNumber($first: Int, $languageCode: LanguageCodeEnum!) {\n  me {\n    orders(first: $first) {\n      edges {\n        node {\n          ...OrderFullDetails\n        }\n      }\n    }\n  }\n}": types.OrderFullDetailsFragmentDoc,
    "fragment OrderDetails on Order {\n  id\n  number\n  created\n  total {\n    gross {\n      amount\n      currency\n    }\n  }\n  lines {\n    variant {\n      id\n      name\n      translation(languageCode: $languageCode) {\n        name\n      }\n      product {\n        id\n        name\n        description\n        slug\n        translation(languageCode: $languageCode) {\n          name\n        }\n        thumbnail(size: 256, format: WEBP) {\n          url\n          alt\n        }\n        category {\n          id\n          name\n        }\n      }\n      pricing {\n        price {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n    }\n    quantity\n  }\n  status\n  statusDisplay\n  paymentStatus\n}": types.OrderDetailsFragmentDoc,
    "query PageGetBySlug($slug: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum) {\n  page(slug: $slug, slugLanguageCode: $slugLanguageCode) {\n    id\n    slug\n    title\n    seoTitle\n    seoDescription\n    content\n    translation(languageCode: $languageCode) {\n      title\n      seoTitle\n      seoDescription\n      content\n      slug\n    }\n    ...PageLocaleSlugTranslations\n  }\n}": types.PageGetBySlugDocument,
    "mutation PasswordChange($newPassword: String!, $oldPassword: String!) {\n  passwordChange(newPassword: $newPassword, oldPassword: $oldPassword) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}": types.PasswordChangeDocument,
    "query ProductDetails($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum) {\n  product(slug: $slug, channel: $channel, slugLanguageCode: $slugLanguageCode) {\n    id\n    name\n    slug\n    description\n    seoTitle\n    seoDescription\n    isAvailable\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoTitle\n      seoDescription\n      slug\n    }\n    ...ProductLocaleSlugTranslations\n    thumbnail(size: 2048, format: WEBP) {\n      url\n      alt\n    }\n    media {\n      url(size: 2048, format: WEBP)\n      url256: url(size: 256, format: WEBP)\n      url512: url(size: 512, format: WEBP)\n      url1024: url(size: 1024, format: WEBP)\n      alt\n      type\n    }\n    category {\n      id\n      name\n      slug\n      translation(languageCode: $languageCode) {\n        name\n        slug\n      }\n    }\n    productType {\n      slug\n    }\n    productVariants(first: 1) {\n      totalCount\n    }\n    bestseller: assignedAttribute(slug: \"bestseller\") {\n      ... on AssignedBooleanAttribute {\n        value\n      }\n    }\n    pulseBestseller: assignedAttribute(slug: \"pulse-bestseller\") {\n      ... on AssignedBooleanAttribute {\n        value\n      }\n    }\n    assignedAttributes(limit: 50) {\n      attribute {\n        name\n        slug\n        translation(languageCode: $languageCode) {\n          name\n        }\n      }\n      ... on AssignedPlainTextAttribute {\n        plainText: value\n        plainTextTranslation: translation(languageCode: $languageCode)\n      }\n      ... on AssignedBooleanAttribute {\n        boolean: value\n      }\n      ... on AssignedNumericAttribute {\n        numeric: value\n      }\n      ... on AssignedSingleChoiceAttribute {\n        choice: value {\n          name\n          slug\n          translation(languageCode: $languageCode)\n        }\n      }\n      ... on AssignedMultiChoiceAttribute {\n        choices: value {\n          name\n          slug\n          translation(languageCode: $languageCode)\n        }\n      }\n    }\n    pricing {\n      priceRange {\n        start {\n          gross {\n            amount\n            currency\n          }\n        }\n        stop {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n    }\n  }\n}": types.ProductDetailsDocument,
    "query ProductList($first: Int = 9, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  products(first: $first, channel: $channel) {\n    edges {\n      node {\n        ...ProductListItem\n      }\n    }\n  }\n}": types.ProductListDocument,
    "query ProductListByCategory($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum, $first: Int, $after: String, $sortBy: ProductOrder, $filter: ProductFilterInput, $where: ProductWhereInput) {\n  category(slug: $slug, slugLanguageCode: $slugLanguageCode) {\n    id\n    name\n    slug\n    description\n    seoDescription\n    seoTitle\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoDescription\n      seoTitle\n      slug\n    }\n    ...CategoryLocaleSlugTranslations\n    backgroundImage(size: 2048, format: WEBP) {\n      url\n      alt\n    }\n    products(\n      first: $first\n      after: $after\n      channel: $channel\n      sortBy: $sortBy\n      filter: $filter\n      where: $where\n    ) {\n      edges {\n        node {\n          ...ProductListItem\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n}": types.ProductListByCategoryDocument,
    "query ProductListByCollection($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum, $first: Int, $after: String, $sortBy: ProductOrder, $filter: ProductFilterInput, $where: ProductWhereInput) {\n  collection(slug: $slug, channel: $channel, slugLanguageCode: $slugLanguageCode) {\n    id\n    name\n    slug\n    description\n    seoDescription\n    seoTitle\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoDescription\n      seoTitle\n      slug\n    }\n    ...CollectionLocaleSlugTranslations\n    backgroundImage(size: 2048, format: WEBP) {\n      url\n      alt\n    }\n    products(\n      first: $first\n      after: $after\n      sortBy: $sortBy\n      filter: $filter\n      where: $where\n    ) {\n      edges {\n        node {\n          ...ProductListItem\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n}": types.ProductListByCollectionDocument,
    "fragment ProductListItem on Product {\n  id\n  name\n  slug\n  created\n  translation(languageCode: $languageCode) {\n    name\n    slug\n  }\n  pricing {\n    priceRange {\n      start {\n        gross {\n          amount\n          currency\n        }\n      }\n      stop {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n    priceRangeUndiscounted {\n      start {\n        gross {\n          amount\n          currency\n        }\n      }\n      stop {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n  }\n  category {\n    id\n    name\n    slug\n    translation(languageCode: $languageCode) {\n      name\n      slug\n    }\n    backgroundImage(size: 1024, format: WEBP) {\n      url\n      alt\n    }\n    backgroundImage256: backgroundImage(size: 256, format: WEBP) {\n      url\n    }\n    backgroundImage512: backgroundImage(size: 512, format: WEBP) {\n      url\n    }\n  }\n  thumbnail(size: 1024, format: WEBP) {\n    url\n    alt\n  }\n  thumbnail256: thumbnail(size: 256, format: WEBP) {\n    url\n  }\n  thumbnail512: thumbnail(size: 512, format: WEBP) {\n    url\n  }\n  bestseller: assignedAttribute(slug: \"bestseller\") {\n    ... on AssignedBooleanAttribute {\n      value\n    }\n  }\n  pulseBestseller: assignedAttribute(slug: \"pulse-bestseller\") {\n    ... on AssignedBooleanAttribute {\n      value\n    }\n  }\n  productVariants(first: 50) {\n    totalCount\n    edges {\n      node {\n        id\n        selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {\n          attribute {\n            slug\n            name\n            inputType\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n          values {\n            name\n            slug\n            value\n            translation(languageCode: $languageCode) {\n              name\n            }\n            file {\n              url\n            }\n          }\n        }\n      }\n    }\n  }\n}": types.ProductListItemFragmentDoc,
    "query ProductListPaginated($first: Int, $after: String, $last: Int, $before: String, $channel: String!, $languageCode: LanguageCodeEnum!, $sortBy: ProductOrder, $filter: ProductFilterInput, $where: ProductWhereInput) {\n  products(\n    first: $first\n    after: $after\n    last: $last\n    before: $before\n    channel: $channel\n    sortBy: $sortBy\n    filter: $filter\n    where: $where\n  ) {\n    totalCount\n    edges {\n      node {\n        ...ProductListItem\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      hasPreviousPage\n      startCursor\n      endCursor\n    }\n  }\n}": types.ProductListPaginatedDocument,
    "query ProductVariantForPdp($id: ID, $sku: String, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  productVariant(id: $id, sku: $sku, channel: $channel) {\n    ...VariantDetails\n    product {\n      id\n      slug\n    }\n  }\n}": types.ProductVariantForPdpDocument,
    "query ProductVariantsForPdp($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $first: Int!, $after: String) {\n  product(slug: $slug, channel: $channel) {\n    id\n    productVariants(first: $first, after: $after) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      edges {\n        node {\n          ...VariantDetails\n        }\n      }\n    }\n  }\n}": types.ProductVariantsForPdpDocument,
    "query SearchProducts($search: String!, $sortBy: ProductOrderField!, $sortDirection: OrderDirection!, $first: Int, $after: String, $last: Int, $before: String, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  products(\n    first: $first\n    after: $after\n    last: $last\n    before: $before\n    channel: $channel\n    sortBy: {field: $sortBy, direction: $sortDirection}\n    filter: {search: $search}\n  ) {\n    totalCount\n    edges {\n      node {\n        ...ProductListItem\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      hasPreviousPage\n      endCursor\n      startCursor\n    }\n  }\n}": types.SearchProductsDocument,
    "query StorefrontContentPages($channel: String!, $slugs: [String!]!, $languageCode: LanguageCodeEnum!) {\n  pages(channel: $channel, where: {slug: {oneOf: $slugs}}, first: 20) {\n    edges {\n      node {\n        ...StorefrontContentPage\n      }\n    }\n  }\n}\n\nfragment StorefrontContentPage on Page {\n  slug\n  isPublished\n  pageType {\n    slug\n  }\n  assignedAttributes {\n    attribute {\n      slug\n    }\n    ... on AssignedPlainTextAttribute {\n      plainText: value\n      plainTextTranslation: translation(languageCode: $languageCode)\n    }\n    ... on AssignedBooleanAttribute {\n      boolean: value\n    }\n    ... on AssignedNumericAttribute {\n      numeric: value\n    }\n    ... on AssignedSingleCollectionReferenceAttribute {\n      collection: value {\n        slug\n      }\n    }\n    ... on AssignedFileAttribute {\n      file: value {\n        url\n      }\n    }\n  }\n}": types.StorefrontContentPagesDocument,
    "fragment UserDetails on User {\n  id\n  email\n  firstName\n  lastName\n  avatar {\n    url\n    alt\n  }\n}": types.UserDetailsFragmentDoc,
    "fragment VariantDetails on ProductVariant {\n  id\n  name\n  sku\n  quantityAvailable\n  translation(languageCode: $languageCode) {\n    name\n  }\n  selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {\n    values {\n      name\n      slug\n      value\n      translation(languageCode: $languageCode) {\n        name\n      }\n      file {\n        url\n      }\n    }\n    attribute {\n      name\n      slug\n      inputType\n      translation(languageCode: $languageCode) {\n        name\n      }\n    }\n  }\n  nonSelectionAttributes: attributes(variantSelection: NOT_VARIANT_SELECTION) {\n    values {\n      name\n      slug\n      value\n      translation(languageCode: $languageCode) {\n        name\n      }\n      file {\n        url\n      }\n    }\n    attribute {\n      name\n      slug\n      inputType\n      translation(languageCode: $languageCode) {\n        name\n      }\n    }\n  }\n  media {\n    url(size: 2048, format: WEBP)\n    url256: url(size: 256, format: WEBP)\n    url512: url(size: 512, format: WEBP)\n    url1024: url(size: 1024, format: WEBP)\n    alt\n    type\n  }\n  pricing {\n    price {\n      gross {\n        currency\n        amount\n      }\n    }\n    priceUndiscounted {\n      gross {\n        currency\n        amount\n      }\n    }\n  }\n}": types.VariantDetailsFragmentDoc,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AccountAddressCreate($input: AddressInput!) {\n  accountAddressCreate(input: $input) {\n    address {\n      ...AddressDetails\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}"): typeof import('./graphql').AccountAddressCreateDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AccountAddressDelete($id: ID!) {\n  accountAddressDelete(id: $id) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}"): typeof import('./graphql').AccountAddressDeleteDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AccountAddressUpdate($id: ID!, $input: AddressInput!) {\n  accountAddressUpdate(id: $id, input: $input) {\n    address {\n      ...AddressDetails\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}"): typeof import('./graphql').AccountAddressUpdateDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AccountRequestDeletion($redirectUrl: String!, $channel: String) {\n  accountRequestDeletion(redirectUrl: $redirectUrl, channel: $channel) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}"): typeof import('./graphql').AccountRequestDeletionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AccountSetDefaultAddress($id: ID!, $type: AddressTypeEnum!) {\n  accountSetDefaultAddress(id: $id, type: $type) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}"): typeof import('./graphql').AccountSetDefaultAddressDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AccountUpdate($input: AccountInput!) {\n  accountUpdate(input: $input) {\n    user {\n      ...UserDetails\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}"): typeof import('./graphql').AccountUpdateDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment AddressDetails on Address {\n  id\n  firstName\n  lastName\n  companyName\n  streetAddress1\n  streetAddress2\n  city\n  cityArea\n  postalCode\n  countryArea\n  country {\n    code\n    country\n  }\n  phone\n}"): typeof import('./graphql').AddressDetailsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CategoriesBySlug($slugs: [String!]!, $first: Int = 20) {\n  categories(filter: {slugs: $slugs}, first: $first) {\n    edges {\n      node {\n        id\n        slug\n        name\n      }\n    }\n  }\n}"): typeof import('./graphql').CategoriesBySlugDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ChannelsList {\n  channels {\n    id\n    name\n    slug\n    isActive\n    currencyCode\n    defaultCountry {\n      code\n    }\n  }\n}"): typeof import('./graphql').ChannelsListDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CheckoutAddLine($id: ID!, $productVariantId: ID!) {\n  checkoutLinesAdd(id: $id, lines: [{quantity: 1, variantId: $productVariantId}]) {\n    checkout {\n      id\n      lines {\n        id\n        quantity\n        variant {\n          name\n          product {\n            name\n          }\n        }\n      }\n    }\n    errors {\n      message\n    }\n  }\n}"): typeof import('./graphql').CheckoutAddLineDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CheckoutCreate($channel: String!, $languageCode: LanguageCodeEnum!, $metadata: [MetadataInput!]) {\n  checkoutCreate(\n    input: {channel: $channel, languageCode: $languageCode, lines: [], metadata: $metadata}\n  ) {\n    checkout {\n      id\n      email\n      lines {\n        id\n        quantity\n        totalPrice {\n          gross {\n            amount\n            currency\n          }\n        }\n        variant {\n          product {\n            id\n            name\n            slug\n            thumbnail(size: 256, format: WEBP) {\n              url\n              alt\n            }\n            category {\n              name\n            }\n          }\n          pricing {\n            price {\n              gross {\n                amount\n                currency\n              }\n            }\n          }\n          name\n          id\n        }\n      }\n      totalPrice {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n    errors {\n      field\n      code\n    }\n  }\n}"): typeof import('./graphql').CheckoutCreateDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CheckoutCustomerDetach($id: ID!) {\n  checkoutCustomerDetach(id: $id) {\n    errors {\n      message\n      field\n      code\n    }\n  }\n}"): typeof import('./graphql').CheckoutCustomerDetachDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CheckoutDeleteLines($checkoutId: ID!, $lineIds: [ID!]!) {\n  checkoutLinesDelete(id: $checkoutId, linesIds: $lineIds) {\n    checkout {\n      id\n      lines {\n        id\n      }\n      channel {\n        slug\n      }\n    }\n    errors {\n      field\n      code\n    }\n  }\n}"): typeof import('./graphql').CheckoutDeleteLinesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CheckoutFind($id: ID!, $languageCode: LanguageCodeEnum!) {\n  checkout(id: $id) {\n    id\n    email\n    lines {\n      id\n      quantity\n      totalPrice {\n        gross {\n          amount\n          currency\n        }\n      }\n      variant {\n        translation(languageCode: $languageCode) {\n          name\n        }\n        product {\n          id\n          name\n          slug\n          translation(languageCode: $languageCode) {\n            name\n          }\n          thumbnail(size: 256, format: WEBP) {\n            url\n            alt\n          }\n          category {\n            name\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n        }\n        pricing {\n          price {\n            gross {\n              amount\n              currency\n            }\n          }\n          priceUndiscounted {\n            gross {\n              amount\n              currency\n            }\n          }\n        }\n        name\n        id\n        selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {\n          attribute {\n            name\n            slug\n            inputType\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n          values {\n            name\n            value\n            translation(languageCode: $languageCode) {\n              name\n            }\n            file {\n              url\n            }\n          }\n        }\n        nonSelectionAttributes: attributes(variantSelection: NOT_VARIANT_SELECTION) {\n          attribute {\n            name\n            slug\n            inputType\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n          values {\n            name\n            value\n            translation(languageCode: $languageCode) {\n              name\n            }\n            file {\n              url\n            }\n          }\n        }\n      }\n    }\n    totalPrice {\n      gross {\n        amount\n        currency\n      }\n    }\n  }\n}"): typeof import('./graphql').CheckoutFindDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CheckoutLinesUpdate($checkoutId: ID!, $lines: [CheckoutLineUpdateInput!]!) {\n  checkoutLinesUpdate(id: $checkoutId, lines: $lines) {\n    checkout {\n      id\n      lines {\n        id\n        quantity\n        totalPrice {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n      totalPrice {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n    errors {\n      field\n      message\n      code\n    }\n  }\n}"): typeof import('./graphql').CheckoutLinesUpdateDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CurrentUser {\n  me {\n    ...UserDetails\n  }\n}"): typeof import('./graphql').CurrentUserDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CurrentUserOrderList($languageCode: LanguageCodeEnum!) {\n  me {\n    ...UserDetails\n    orders(first: 10) {\n      edges {\n        node {\n          ...OrderDetails\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').CurrentUserOrderListDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CurrentUserOrdersPaginated($first: Int, $after: String, $languageCode: LanguageCodeEnum!) {\n  me {\n    ...UserDetails\n    orders(first: $first, after: $after) {\n      edges {\n        node {\n          ...OrderDetails\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n}"): typeof import('./graphql').CurrentUserOrdersPaginatedDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CurrentUserProfile {\n  me {\n    ...UserDetails\n    dateJoined\n    addresses {\n      ...AddressDetails\n    }\n    defaultShippingAddress {\n      id\n    }\n    defaultBillingAddress {\n      id\n    }\n  }\n}"): typeof import('./graphql').CurrentUserProfileDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment ProductLocaleSlugTranslations on Product {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}\n\nfragment CategoryLocaleSlugTranslations on Category {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}\n\nfragment CollectionLocaleSlugTranslations on Collection {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}\n\nfragment PageLocaleSlugTranslations on Page {\n  slugEN: translation(languageCode: EN) {\n    slug\n  }\n  slugPL: translation(languageCode: PL) {\n    slug\n  }\n  slugDE: translation(languageCode: DE) {\n    slug\n  }\n  slugFR: translation(languageCode: FR) {\n    slug\n  }\n  slugFI: translation(languageCode: FI) {\n    slug\n  }\n  slugNB: translation(languageCode: NB) {\n    slug\n  }\n  slugJA: translation(languageCode: JA) {\n    slug\n  }\n  slugKO: translation(languageCode: KO) {\n    slug\n  }\n}"): typeof import('./graphql').ProductLocaleSlugTranslationsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment MenuItem on MenuItem {\n  id\n  name\n  level\n  translation(languageCode: $languageCode) {\n    name\n  }\n  category {\n    id\n    slug\n    name\n    translation(languageCode: $languageCode) {\n      name\n      slug\n    }\n  }\n  collection {\n    id\n    name\n    slug\n    translation(languageCode: $languageCode) {\n      name\n      slug\n    }\n  }\n  page {\n    id\n    title\n    slug\n    translation(languageCode: $languageCode) {\n      title\n      slug\n    }\n  }\n  url\n}\n\nquery MenuGetBySlug($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  menu(slug: $slug, channel: $channel) {\n    items {\n      ...MenuItem\n      children {\n        ...MenuItem\n        children {\n          ...MenuItem\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').MenuItemFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment OrderFullDetails on Order {\n  id\n  number\n  created\n  status\n  statusDisplay\n  paymentStatus\n  isPaid\n  shippingAddress {\n    ...AddressDetails\n  }\n  billingAddress {\n    ...AddressDetails\n  }\n  subtotal {\n    gross {\n      amount\n      currency\n    }\n  }\n  shippingPrice {\n    gross {\n      amount\n      currency\n    }\n  }\n  total {\n    gross {\n      amount\n      currency\n    }\n    tax {\n      amount\n      currency\n    }\n  }\n  lines {\n    id\n    quantity\n    variant {\n      id\n      name\n      translation(languageCode: $languageCode) {\n        name\n      }\n      product {\n        id\n        name\n        slug\n        translation(languageCode: $languageCode) {\n          name\n        }\n        thumbnail(size: 256, format: WEBP) {\n          url\n          alt\n        }\n      }\n      pricing {\n        price {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n    }\n  }\n  fulfillments {\n    id\n    status\n    created\n    trackingNumber\n    lines {\n      id\n      quantity\n      orderLine {\n        id\n      }\n    }\n  }\n}\n\nquery OrderByNumber($first: Int, $languageCode: LanguageCodeEnum!) {\n  me {\n    orders(first: $first) {\n      edges {\n        node {\n          ...OrderFullDetails\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').OrderFullDetailsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment OrderDetails on Order {\n  id\n  number\n  created\n  total {\n    gross {\n      amount\n      currency\n    }\n  }\n  lines {\n    variant {\n      id\n      name\n      translation(languageCode: $languageCode) {\n        name\n      }\n      product {\n        id\n        name\n        description\n        slug\n        translation(languageCode: $languageCode) {\n          name\n        }\n        thumbnail(size: 256, format: WEBP) {\n          url\n          alt\n        }\n        category {\n          id\n          name\n        }\n      }\n      pricing {\n        price {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n    }\n    quantity\n  }\n  status\n  statusDisplay\n  paymentStatus\n}"): typeof import('./graphql').OrderDetailsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query PageGetBySlug($slug: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum) {\n  page(slug: $slug, slugLanguageCode: $slugLanguageCode) {\n    id\n    slug\n    title\n    seoTitle\n    seoDescription\n    content\n    translation(languageCode: $languageCode) {\n      title\n      seoTitle\n      seoDescription\n      content\n      slug\n    }\n    ...PageLocaleSlugTranslations\n  }\n}"): typeof import('./graphql').PageGetBySlugDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation PasswordChange($newPassword: String!, $oldPassword: String!) {\n  passwordChange(newPassword: $newPassword, oldPassword: $oldPassword) {\n    errors {\n      field\n      message\n      code\n    }\n  }\n}"): typeof import('./graphql').PasswordChangeDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ProductDetails($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum) {\n  product(slug: $slug, channel: $channel, slugLanguageCode: $slugLanguageCode) {\n    id\n    name\n    slug\n    description\n    seoTitle\n    seoDescription\n    isAvailable\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoTitle\n      seoDescription\n      slug\n    }\n    ...ProductLocaleSlugTranslations\n    thumbnail(size: 2048, format: WEBP) {\n      url\n      alt\n    }\n    media {\n      url(size: 2048, format: WEBP)\n      url256: url(size: 256, format: WEBP)\n      url512: url(size: 512, format: WEBP)\n      url1024: url(size: 1024, format: WEBP)\n      alt\n      type\n    }\n    category {\n      id\n      name\n      slug\n      translation(languageCode: $languageCode) {\n        name\n        slug\n      }\n    }\n    productType {\n      slug\n    }\n    productVariants(first: 1) {\n      totalCount\n    }\n    bestseller: assignedAttribute(slug: \"bestseller\") {\n      ... on AssignedBooleanAttribute {\n        value\n      }\n    }\n    pulseBestseller: assignedAttribute(slug: \"pulse-bestseller\") {\n      ... on AssignedBooleanAttribute {\n        value\n      }\n    }\n    assignedAttributes(limit: 50) {\n      attribute {\n        name\n        slug\n        translation(languageCode: $languageCode) {\n          name\n        }\n      }\n      ... on AssignedPlainTextAttribute {\n        plainText: value\n        plainTextTranslation: translation(languageCode: $languageCode)\n      }\n      ... on AssignedBooleanAttribute {\n        boolean: value\n      }\n      ... on AssignedNumericAttribute {\n        numeric: value\n      }\n      ... on AssignedSingleChoiceAttribute {\n        choice: value {\n          name\n          slug\n          translation(languageCode: $languageCode)\n        }\n      }\n      ... on AssignedMultiChoiceAttribute {\n        choices: value {\n          name\n          slug\n          translation(languageCode: $languageCode)\n        }\n      }\n    }\n    pricing {\n      priceRange {\n        start {\n          gross {\n            amount\n            currency\n          }\n        }\n        stop {\n          gross {\n            amount\n            currency\n          }\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').ProductDetailsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ProductList($first: Int = 9, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  products(first: $first, channel: $channel) {\n    edges {\n      node {\n        ...ProductListItem\n      }\n    }\n  }\n}"): typeof import('./graphql').ProductListDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ProductListByCategory($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum, $first: Int, $after: String, $sortBy: ProductOrder, $filter: ProductFilterInput, $where: ProductWhereInput) {\n  category(slug: $slug, slugLanguageCode: $slugLanguageCode) {\n    id\n    name\n    slug\n    description\n    seoDescription\n    seoTitle\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoDescription\n      seoTitle\n      slug\n    }\n    ...CategoryLocaleSlugTranslations\n    backgroundImage(size: 2048, format: WEBP) {\n      url\n      alt\n    }\n    products(\n      first: $first\n      after: $after\n      channel: $channel\n      sortBy: $sortBy\n      filter: $filter\n      where: $where\n    ) {\n      edges {\n        node {\n          ...ProductListItem\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n}"): typeof import('./graphql').ProductListByCategoryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ProductListByCollection($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $slugLanguageCode: LanguageCodeEnum, $first: Int, $after: String, $sortBy: ProductOrder, $filter: ProductFilterInput, $where: ProductWhereInput) {\n  collection(slug: $slug, channel: $channel, slugLanguageCode: $slugLanguageCode) {\n    id\n    name\n    slug\n    description\n    seoDescription\n    seoTitle\n    translation(languageCode: $languageCode) {\n      name\n      description\n      seoDescription\n      seoTitle\n      slug\n    }\n    ...CollectionLocaleSlugTranslations\n    backgroundImage(size: 2048, format: WEBP) {\n      url\n      alt\n    }\n    products(\n      first: $first\n      after: $after\n      sortBy: $sortBy\n      filter: $filter\n      where: $where\n    ) {\n      edges {\n        node {\n          ...ProductListItem\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n}"): typeof import('./graphql').ProductListByCollectionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment ProductListItem on Product {\n  id\n  name\n  slug\n  created\n  translation(languageCode: $languageCode) {\n    name\n    slug\n  }\n  pricing {\n    priceRange {\n      start {\n        gross {\n          amount\n          currency\n        }\n      }\n      stop {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n    priceRangeUndiscounted {\n      start {\n        gross {\n          amount\n          currency\n        }\n      }\n      stop {\n        gross {\n          amount\n          currency\n        }\n      }\n    }\n  }\n  category {\n    id\n    name\n    slug\n    translation(languageCode: $languageCode) {\n      name\n      slug\n    }\n    backgroundImage(size: 1024, format: WEBP) {\n      url\n      alt\n    }\n    backgroundImage256: backgroundImage(size: 256, format: WEBP) {\n      url\n    }\n    backgroundImage512: backgroundImage(size: 512, format: WEBP) {\n      url\n    }\n  }\n  thumbnail(size: 1024, format: WEBP) {\n    url\n    alt\n  }\n  thumbnail256: thumbnail(size: 256, format: WEBP) {\n    url\n  }\n  thumbnail512: thumbnail(size: 512, format: WEBP) {\n    url\n  }\n  bestseller: assignedAttribute(slug: \"bestseller\") {\n    ... on AssignedBooleanAttribute {\n      value\n    }\n  }\n  pulseBestseller: assignedAttribute(slug: \"pulse-bestseller\") {\n    ... on AssignedBooleanAttribute {\n      value\n    }\n  }\n  productVariants(first: 50) {\n    totalCount\n    edges {\n      node {\n        id\n        selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {\n          attribute {\n            slug\n            name\n            inputType\n            translation(languageCode: $languageCode) {\n              name\n            }\n          }\n          values {\n            name\n            slug\n            value\n            translation(languageCode: $languageCode) {\n              name\n            }\n            file {\n              url\n            }\n          }\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').ProductListItemFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ProductListPaginated($first: Int, $after: String, $last: Int, $before: String, $channel: String!, $languageCode: LanguageCodeEnum!, $sortBy: ProductOrder, $filter: ProductFilterInput, $where: ProductWhereInput) {\n  products(\n    first: $first\n    after: $after\n    last: $last\n    before: $before\n    channel: $channel\n    sortBy: $sortBy\n    filter: $filter\n    where: $where\n  ) {\n    totalCount\n    edges {\n      node {\n        ...ProductListItem\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      hasPreviousPage\n      startCursor\n      endCursor\n    }\n  }\n}"): typeof import('./graphql').ProductListPaginatedDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ProductVariantForPdp($id: ID, $sku: String, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  productVariant(id: $id, sku: $sku, channel: $channel) {\n    ...VariantDetails\n    product {\n      id\n      slug\n    }\n  }\n}"): typeof import('./graphql').ProductVariantForPdpDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query ProductVariantsForPdp($slug: String!, $channel: String!, $languageCode: LanguageCodeEnum!, $first: Int!, $after: String) {\n  product(slug: $slug, channel: $channel) {\n    id\n    productVariants(first: $first, after: $after) {\n      totalCount\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      edges {\n        node {\n          ...VariantDetails\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').ProductVariantsForPdpDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query SearchProducts($search: String!, $sortBy: ProductOrderField!, $sortDirection: OrderDirection!, $first: Int, $after: String, $last: Int, $before: String, $channel: String!, $languageCode: LanguageCodeEnum!) {\n  products(\n    first: $first\n    after: $after\n    last: $last\n    before: $before\n    channel: $channel\n    sortBy: {field: $sortBy, direction: $sortDirection}\n    filter: {search: $search}\n  ) {\n    totalCount\n    edges {\n      node {\n        ...ProductListItem\n      }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      hasPreviousPage\n      endCursor\n      startCursor\n    }\n  }\n}"): typeof import('./graphql').SearchProductsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query StorefrontContentPages($channel: String!, $slugs: [String!]!, $languageCode: LanguageCodeEnum!) {\n  pages(channel: $channel, where: {slug: {oneOf: $slugs}}, first: 20) {\n    edges {\n      node {\n        ...StorefrontContentPage\n      }\n    }\n  }\n}\n\nfragment StorefrontContentPage on Page {\n  slug\n  isPublished\n  pageType {\n    slug\n  }\n  assignedAttributes {\n    attribute {\n      slug\n    }\n    ... on AssignedPlainTextAttribute {\n      plainText: value\n      plainTextTranslation: translation(languageCode: $languageCode)\n    }\n    ... on AssignedBooleanAttribute {\n      boolean: value\n    }\n    ... on AssignedNumericAttribute {\n      numeric: value\n    }\n    ... on AssignedSingleCollectionReferenceAttribute {\n      collection: value {\n        slug\n      }\n    }\n    ... on AssignedFileAttribute {\n      file: value {\n        url\n      }\n    }\n  }\n}"): typeof import('./graphql').StorefrontContentPagesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment UserDetails on User {\n  id\n  email\n  firstName\n  lastName\n  avatar {\n    url\n    alt\n  }\n}"): typeof import('./graphql').UserDetailsFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment VariantDetails on ProductVariant {\n  id\n  name\n  sku\n  quantityAvailable\n  translation(languageCode: $languageCode) {\n    name\n  }\n  selectionAttributes: attributes(variantSelection: VARIANT_SELECTION) {\n    values {\n      name\n      slug\n      value\n      translation(languageCode: $languageCode) {\n        name\n      }\n      file {\n        url\n      }\n    }\n    attribute {\n      name\n      slug\n      inputType\n      translation(languageCode: $languageCode) {\n        name\n      }\n    }\n  }\n  nonSelectionAttributes: attributes(variantSelection: NOT_VARIANT_SELECTION) {\n    values {\n      name\n      slug\n      value\n      translation(languageCode: $languageCode) {\n        name\n      }\n      file {\n        url\n      }\n    }\n    attribute {\n      name\n      slug\n      inputType\n      translation(languageCode: $languageCode) {\n        name\n      }\n    }\n  }\n  media {\n    url(size: 2048, format: WEBP)\n    url256: url(size: 256, format: WEBP)\n    url512: url(size: 512, format: WEBP)\n    url1024: url(size: 1024, format: WEBP)\n    alt\n    type\n  }\n  pricing {\n    price {\n      gross {\n        currency\n        amount\n      }\n    }\n    priceUndiscounted {\n      gross {\n        currency\n        amount\n      }\n    }\n  }\n}"): typeof import('./graphql').VariantDetailsFragmentDoc;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
